package anonymous.developer.mapper;

import anonymous.developer.model.Case;
import anonymous.developer.model.CaseExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    long countByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    int deleteByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    int deleteByPrimaryKey(Integer caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    int insert(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    int insertSelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    List<Case> selectByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    Case selectByPrimaryKey(Integer caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Case record, @Param("example") CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    int updateByExample(@Param("record") Case record, @Param("example") CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    int updateByPrimaryKeySelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    int updateByPrimaryKey(Case record);
}