package anonymous.developer.mapper;

import anonymous.developer.model.CaseClassification;
import anonymous.developer.model.CaseClassificationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CaseClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    long countByExample(CaseClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    int deleteByExample(CaseClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    int deleteByPrimaryKey(Integer caseClassificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    int insert(CaseClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    int insertSelective(CaseClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    List<CaseClassification> selectByExample(CaseClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    CaseClassification selectByPrimaryKey(Integer caseClassificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") CaseClassification record, @Param("example") CaseClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    int updateByExample(@Param("record") CaseClassification record, @Param("example") CaseClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    int updateByPrimaryKeySelective(CaseClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_classification
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    int updateByPrimaryKey(CaseClassification record);
}