package anonymous.developer.mapper;

import anonymous.developer.model.CompanyInformation;
import anonymous.developer.model.CompanyInformationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CompanyInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    long countByExample(CompanyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    int deleteByExample(CompanyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    int insert(CompanyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    int insertSelective(CompanyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    List<CompanyInformation> selectByExample(CompanyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    CompanyInformation selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") CompanyInformation record, @Param("example") CompanyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    int updateByExample(@Param("record") CompanyInformation record, @Param("example") CompanyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    int updateByPrimaryKeySelective(CompanyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    int updateByPrimaryKey(CompanyInformation record);
}