package anonymous.developer.mapper;

import anonymous.developer.model.Navigation;
import anonymous.developer.model.NavigationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface NavigationMapper {

    /**
     * 返回所有的导航数据
     * @return 导航数据
     */
    List<Navigation> selectAll();

    /**
     * 分页查询导航数据
     * @param ignore
     * @param size
     * @return 导航数据
     */
    List<Navigation> selectLimit(@Param("ignore") Integer ignore,@Param("size") Integer size);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    long countByExample(NavigationExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    int deleteByExample(NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    int deleteByPrimaryKey(Integer navigationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    int insert(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    int insertSelective(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    List<Navigation> selectByExample(NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    Navigation selectByPrimaryKey(Integer navigationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") Navigation record, @Param("example") NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    int updateByExample(@Param("record") Navigation record, @Param("example") NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    int updateByPrimaryKeySelective(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    int updateByPrimaryKey(Navigation record);
}