package anonymous.developer.mapper;

import anonymous.developer.model.NewsClassification;
import anonymous.developer.model.NewsClassificationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface NewsClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    long countByExample(NewsClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    int deleteByExample(NewsClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    int deleteByPrimaryKey(Integer newsClassificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    int insert(NewsClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    int insertSelective(NewsClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    List<NewsClassification> selectByExample(NewsClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    NewsClassification selectByPrimaryKey(Integer newsClassificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") NewsClassification record, @Param("example") NewsClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    int updateByExample(@Param("record") NewsClassification record, @Param("example") NewsClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    int updateByPrimaryKeySelective(NewsClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    int updateByPrimaryKey(NewsClassification record);
}