package anonymous.developer.mapper;

import anonymous.developer.model.NewsLabel;
import anonymous.developer.model.NewsLabelExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface NewsLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    long countByExample(NewsLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    int deleteByExample(NewsLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    int deleteByPrimaryKey(Integer newsLabelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    int insert(NewsLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    int insertSelective(NewsLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    List<NewsLabel> selectByExample(NewsLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    NewsLabel selectByPrimaryKey(Integer newsLabelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") NewsLabel record, @Param("example") NewsLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    int updateByExample(@Param("record") NewsLabel record, @Param("example") NewsLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    int updateByPrimaryKeySelective(NewsLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_label
     *
     * @mbg.generated Sat Jun 15 02:55:45 CST 2019
     */
    int updateByPrimaryKey(NewsLabel record);
}