package anonymous.developer.mapper;

import anonymous.developer.model.Permission;
import anonymous.developer.model.PermissionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface PermissionMapper {
    /**
     * 选择所有权限数据
     * @return 权限数据
     */
    List<Permission> selectAll();

    /**
     * 分页选择权限数据
     * @param startRow 起始行
     * @param pageSize 分页大小
     * @return 权限数据
     */
    List<Permission> selectLimit(@Param("startRow") Integer startRow,@Param("pageSize") Integer pageSize);

    /**
     * 通过角色ID选择权限数据
     * @param roleId 角色ID
     * @return 权限数据
     */
    List<Permission> selectByRoleId(@Param("roleId")Integer roleId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    long countByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    int deleteByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    int deleteByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    List<Permission> selectByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    Permission selectByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    int updateByPrimaryKey(Permission record);
}