package anonymous.developer.mapper;

import anonymous.developer.model.SystemInformation;
import anonymous.developer.model.SystemInformationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import java.util.List;

@Mapper
public interface SystemInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    long countByExample(SystemInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    int deleteByExample(SystemInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    int deleteByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    int insert(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    int insertSelective(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    List<SystemInformation> selectByExample(SystemInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    SystemInformation selectByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") SystemInformation record, @Param("example") SystemInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    int updateByExample(@Param("record") SystemInformation record, @Param("example") SystemInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    int updateByPrimaryKeySelective(SystemInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    int updateByPrimaryKey(SystemInformation record);
}