package anonymous.developer.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public CaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCaseIdIsNull() {
            addCriterion("case_id is null");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNotNull() {
            addCriterion("case_id is not null");
            return (Criteria) this;
        }

        public Criteria andCaseIdEqualTo(Integer value) {
            addCriterion("case_id =", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotEqualTo(Integer value) {
            addCriterion("case_id <>", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThan(Integer value) {
            addCriterion("case_id >", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("case_id >=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThan(Integer value) {
            addCriterion("case_id <", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThanOrEqualTo(Integer value) {
            addCriterion("case_id <=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdIn(List<Integer> values) {
            addCriterion("case_id in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotIn(List<Integer> values) {
            addCriterion("case_id not in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdBetween(Integer value1, Integer value2) {
            addCriterion("case_id between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("case_id not between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseCoverIsNull() {
            addCriterion("case_cover is null");
            return (Criteria) this;
        }

        public Criteria andCaseCoverIsNotNull() {
            addCriterion("case_cover is not null");
            return (Criteria) this;
        }

        public Criteria andCaseCoverEqualTo(String value) {
            addCriterion("case_cover =", value, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverNotEqualTo(String value) {
            addCriterion("case_cover <>", value, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverGreaterThan(String value) {
            addCriterion("case_cover >", value, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverGreaterThanOrEqualTo(String value) {
            addCriterion("case_cover >=", value, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverLessThan(String value) {
            addCriterion("case_cover <", value, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverLessThanOrEqualTo(String value) {
            addCriterion("case_cover <=", value, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverLike(String value) {
            addCriterion("case_cover like", value, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverNotLike(String value) {
            addCriterion("case_cover not like", value, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverIn(List<String> values) {
            addCriterion("case_cover in", values, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverNotIn(List<String> values) {
            addCriterion("case_cover not in", values, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverBetween(String value1, String value2) {
            addCriterion("case_cover between", value1, value2, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseCoverNotBetween(String value1, String value2) {
            addCriterion("case_cover not between", value1, value2, "caseCover");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNull() {
            addCriterion("case_name is null");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNotNull() {
            addCriterion("case_name is not null");
            return (Criteria) this;
        }

        public Criteria andCaseNameEqualTo(String value) {
            addCriterion("case_name =", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotEqualTo(String value) {
            addCriterion("case_name <>", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThan(String value) {
            addCriterion("case_name >", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThanOrEqualTo(String value) {
            addCriterion("case_name >=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThan(String value) {
            addCriterion("case_name <", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThanOrEqualTo(String value) {
            addCriterion("case_name <=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLike(String value) {
            addCriterion("case_name like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotLike(String value) {
            addCriterion("case_name not like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameIn(List<String> values) {
            addCriterion("case_name in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotIn(List<String> values) {
            addCriterion("case_name not in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameBetween(String value1, String value2) {
            addCriterion("case_name between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotBetween(String value1, String value2) {
            addCriterion("case_name not between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseContentIsNull() {
            addCriterion("case_content is null");
            return (Criteria) this;
        }

        public Criteria andCaseContentIsNotNull() {
            addCriterion("case_content is not null");
            return (Criteria) this;
        }

        public Criteria andCaseContentEqualTo(String value) {
            addCriterion("case_content =", value, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentNotEqualTo(String value) {
            addCriterion("case_content <>", value, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentGreaterThan(String value) {
            addCriterion("case_content >", value, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentGreaterThanOrEqualTo(String value) {
            addCriterion("case_content >=", value, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentLessThan(String value) {
            addCriterion("case_content <", value, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentLessThanOrEqualTo(String value) {
            addCriterion("case_content <=", value, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentLike(String value) {
            addCriterion("case_content like", value, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentNotLike(String value) {
            addCriterion("case_content not like", value, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentIn(List<String> values) {
            addCriterion("case_content in", values, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentNotIn(List<String> values) {
            addCriterion("case_content not in", values, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentBetween(String value1, String value2) {
            addCriterion("case_content between", value1, value2, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseContentNotBetween(String value1, String value2) {
            addCriterion("case_content not between", value1, value2, "caseContent");
            return (Criteria) this;
        }

        public Criteria andCaseLinkIsNull() {
            addCriterion("case_link is null");
            return (Criteria) this;
        }

        public Criteria andCaseLinkIsNotNull() {
            addCriterion("case_link is not null");
            return (Criteria) this;
        }

        public Criteria andCaseLinkEqualTo(String value) {
            addCriterion("case_link =", value, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkNotEqualTo(String value) {
            addCriterion("case_link <>", value, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkGreaterThan(String value) {
            addCriterion("case_link >", value, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkGreaterThanOrEqualTo(String value) {
            addCriterion("case_link >=", value, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkLessThan(String value) {
            addCriterion("case_link <", value, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkLessThanOrEqualTo(String value) {
            addCriterion("case_link <=", value, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkLike(String value) {
            addCriterion("case_link like", value, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkNotLike(String value) {
            addCriterion("case_link not like", value, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkIn(List<String> values) {
            addCriterion("case_link in", values, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkNotIn(List<String> values) {
            addCriterion("case_link not in", values, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkBetween(String value1, String value2) {
            addCriterion("case_link between", value1, value2, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCaseLinkNotBetween(String value1, String value2) {
            addCriterion("case_link not between", value1, value2, "caseLink");
            return (Criteria) this;
        }

        public Criteria andCasePersonIsNull() {
            addCriterion("case_person is null");
            return (Criteria) this;
        }

        public Criteria andCasePersonIsNotNull() {
            addCriterion("case_person is not null");
            return (Criteria) this;
        }

        public Criteria andCasePersonEqualTo(String value) {
            addCriterion("case_person =", value, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonNotEqualTo(String value) {
            addCriterion("case_person <>", value, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonGreaterThan(String value) {
            addCriterion("case_person >", value, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonGreaterThanOrEqualTo(String value) {
            addCriterion("case_person >=", value, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonLessThan(String value) {
            addCriterion("case_person <", value, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonLessThanOrEqualTo(String value) {
            addCriterion("case_person <=", value, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonLike(String value) {
            addCriterion("case_person like", value, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonNotLike(String value) {
            addCriterion("case_person not like", value, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonIn(List<String> values) {
            addCriterion("case_person in", values, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonNotIn(List<String> values) {
            addCriterion("case_person not in", values, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonBetween(String value1, String value2) {
            addCriterion("case_person between", value1, value2, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCasePersonNotBetween(String value1, String value2) {
            addCriterion("case_person not between", value1, value2, "casePerson");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyIsNull() {
            addCriterion("case_technology is null");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyIsNotNull() {
            addCriterion("case_technology is not null");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyEqualTo(String value) {
            addCriterion("case_technology =", value, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyNotEqualTo(String value) {
            addCriterion("case_technology <>", value, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyGreaterThan(String value) {
            addCriterion("case_technology >", value, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyGreaterThanOrEqualTo(String value) {
            addCriterion("case_technology >=", value, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyLessThan(String value) {
            addCriterion("case_technology <", value, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyLessThanOrEqualTo(String value) {
            addCriterion("case_technology <=", value, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyLike(String value) {
            addCriterion("case_technology like", value, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyNotLike(String value) {
            addCriterion("case_technology not like", value, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyIn(List<String> values) {
            addCriterion("case_technology in", values, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyNotIn(List<String> values) {
            addCriterion("case_technology not in", values, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyBetween(String value1, String value2) {
            addCriterion("case_technology between", value1, value2, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseTechnologyNotBetween(String value1, String value2) {
            addCriterion("case_technology not between", value1, value2, "caseTechnology");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeIsNull() {
            addCriterion("case_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeIsNotNull() {
            addCriterion("case_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeEqualTo(Date value) {
            addCriterion("case_datetime =", value, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeNotEqualTo(Date value) {
            addCriterion("case_datetime <>", value, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeGreaterThan(Date value) {
            addCriterion("case_datetime >", value, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("case_datetime >=", value, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeLessThan(Date value) {
            addCriterion("case_datetime <", value, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("case_datetime <=", value, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeIn(List<Date> values) {
            addCriterion("case_datetime in", values, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeNotIn(List<Date> values) {
            addCriterion("case_datetime not in", values, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeBetween(Date value1, Date value2) {
            addCriterion("case_datetime between", value1, value2, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("case_datetime not between", value1, value2, "caseDatetime");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdIsNull() {
            addCriterion("case_classification_id is null");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdIsNotNull() {
            addCriterion("case_classification_id is not null");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdEqualTo(Integer value) {
            addCriterion("case_classification_id =", value, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdNotEqualTo(Integer value) {
            addCriterion("case_classification_id <>", value, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdGreaterThan(Integer value) {
            addCriterion("case_classification_id >", value, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("case_classification_id >=", value, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdLessThan(Integer value) {
            addCriterion("case_classification_id <", value, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdLessThanOrEqualTo(Integer value) {
            addCriterion("case_classification_id <=", value, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdIn(List<Integer> values) {
            addCriterion("case_classification_id in", values, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdNotIn(List<Integer> values) {
            addCriterion("case_classification_id not in", values, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdBetween(Integer value1, Integer value2) {
            addCriterion("case_classification_id between", value1, value2, "caseClassificationId");
            return (Criteria) this;
        }

        public Criteria andCaseClassificationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("case_classification_id not between", value1, value2, "caseClassificationId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cases
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 15 02:58:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cases
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}