package anonymous.developer.model;

public class CasePicture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_picture.case_picture_id
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    private Integer casePictureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_picture.case_picture_url
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    private String casePictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_picture.case_id
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    private Integer caseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_picture.case_picture_id
     *
     * @return the value of case_picture.case_picture_id
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    public Integer getCasePictureId() {
        return casePictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_picture.case_picture_id
     *
     * @param casePictureId the value for case_picture.case_picture_id
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    public void setCasePictureId(Integer casePictureId) {
        this.casePictureId = casePictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_picture.case_picture_url
     *
     * @return the value of case_picture.case_picture_url
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    public String getCasePictureUrl() {
        return casePictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_picture.case_picture_url
     *
     * @param casePictureUrl the value for case_picture.case_picture_url
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    public void setCasePictureUrl(String casePictureUrl) {
        this.casePictureUrl = casePictureUrl == null ? null : casePictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_picture.case_id
     *
     * @return the value of case_picture.case_id
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_picture.case_id
     *
     * @param caseId the value for case_picture.case_id
     *
     * @mbg.generated Sat Jun 15 02:59:09 CST 2019
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }
}