package anonymous.developer.model;

public class CaseClassification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_classification.case_classification_id
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    private Integer caseClassificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_classification.case_classification_name
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    private String caseClassificationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_classification.case_classification_id
     *
     * @return the value of case_classification.case_classification_id
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    public Integer getCaseClassificationId() {
        return caseClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_classification.case_classification_id
     *
     * @param caseClassificationId the value for case_classification.case_classification_id
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    public void setCaseClassificationId(Integer caseClassificationId) {
        this.caseClassificationId = caseClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_classification.case_classification_name
     *
     * @return the value of case_classification.case_classification_name
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    public String getCaseClassificationName() {
        return caseClassificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_classification.case_classification_name
     *
     * @param caseClassificationName the value for case_classification.case_classification_name
     *
     * @mbg.generated Sat Jun 15 02:58:20 CST 2019
     */
    public void setCaseClassificationName(String caseClassificationName) {
        this.caseClassificationName = caseClassificationName == null ? null : caseClassificationName.trim();
    }
}