package anonymous.developer.model;

import java.util.Date;

public class Case {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_id
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private Integer caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_cover
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private String caseCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_name
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private String caseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_content
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private String caseContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_link
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private String caseLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_person
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private String casePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_technology
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private String caseTechnology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_datetime
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private Date caseDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_classification_id
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    private Integer caseClassificationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_id
     *
     * @return the value of cases.case_id
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_id
     *
     * @param caseId the value for cases.case_id
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_cover
     *
     * @return the value of cases.case_cover
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public String getCaseCover() {
        return caseCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_cover
     *
     * @param caseCover the value for cases.case_cover
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCaseCover(String caseCover) {
        this.caseCover = caseCover == null ? null : caseCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_name
     *
     * @return the value of cases.case_name
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_name
     *
     * @param caseName the value for cases.case_name
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_content
     *
     * @return the value of cases.case_content
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public String getCaseContent() {
        return caseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_content
     *
     * @param caseContent the value for cases.case_content
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCaseContent(String caseContent) {
        this.caseContent = caseContent == null ? null : caseContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_link
     *
     * @return the value of cases.case_link
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public String getCaseLink() {
        return caseLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_link
     *
     * @param caseLink the value for cases.case_link
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCaseLink(String caseLink) {
        this.caseLink = caseLink == null ? null : caseLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_person
     *
     * @return the value of cases.case_person
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public String getCasePerson() {
        return casePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_person
     *
     * @param casePerson the value for cases.case_person
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCasePerson(String casePerson) {
        this.casePerson = casePerson == null ? null : casePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_technology
     *
     * @return the value of cases.case_technology
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public String getCaseTechnology() {
        return caseTechnology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_technology
     *
     * @param caseTechnology the value for cases.case_technology
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCaseTechnology(String caseTechnology) {
        this.caseTechnology = caseTechnology == null ? null : caseTechnology.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_datetime
     *
     * @return the value of cases.case_datetime
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public Date getCaseDatetime() {
        return caseDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_datetime
     *
     * @param caseDatetime the value for cases.case_datetime
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCaseDatetime(Date caseDatetime) {
        this.caseDatetime = caseDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_classification_id
     *
     * @return the value of cases.case_classification_id
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public Integer getCaseClassificationId() {
        return caseClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.case_classification_id
     *
     * @param caseClassificationId the value for cases.case_classification_id
     *
     * @mbg.generated Sat Jun 15 02:58:43 CST 2019
     */
    public void setCaseClassificationId(Integer caseClassificationId) {
        this.caseClassificationId = caseClassificationId;
    }
}