package anonymous.developer.model;

import java.math.BigDecimal;

public class CompanyInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_id
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_name
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_logo
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_contact_phone
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyContactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_contact_qq
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyContactQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_email
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_address
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_qrcode
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyQrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_master
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyMaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_keyword
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyKeyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_description
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_icp
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyIcp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.ompany_latitude
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private BigDecimal ompanyLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_longitude
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private BigDecimal companyLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_information.company_wechat
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    private String companyWechat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_id
     *
     * @return the value of company_information.company_id
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_id
     *
     * @param companyId the value for company_information.company_id
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_name
     *
     * @return the value of company_information.company_name
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_name
     *
     * @param companyName the value for company_information.company_name
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_logo
     *
     * @return the value of company_information.company_logo
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyLogo() {
        return companyLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_logo
     *
     * @param companyLogo the value for company_information.company_logo
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyLogo(String companyLogo) {
        this.companyLogo = companyLogo == null ? null : companyLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_contact_phone
     *
     * @return the value of company_information.company_contact_phone
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyContactPhone() {
        return companyContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_contact_phone
     *
     * @param companyContactPhone the value for company_information.company_contact_phone
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyContactPhone(String companyContactPhone) {
        this.companyContactPhone = companyContactPhone == null ? null : companyContactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_contact_qq
     *
     * @return the value of company_information.company_contact_qq
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyContactQq() {
        return companyContactQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_contact_qq
     *
     * @param companyContactQq the value for company_information.company_contact_qq
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyContactQq(String companyContactQq) {
        this.companyContactQq = companyContactQq == null ? null : companyContactQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_email
     *
     * @return the value of company_information.company_email
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyEmail() {
        return companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_email
     *
     * @param companyEmail the value for company_information.company_email
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail == null ? null : companyEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_address
     *
     * @return the value of company_information.company_address
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_address
     *
     * @param companyAddress the value for company_information.company_address
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_qrcode
     *
     * @return the value of company_information.company_qrcode
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyQrcode() {
        return companyQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_qrcode
     *
     * @param companyQrcode the value for company_information.company_qrcode
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyQrcode(String companyQrcode) {
        this.companyQrcode = companyQrcode == null ? null : companyQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_master
     *
     * @return the value of company_information.company_master
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyMaster() {
        return companyMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_master
     *
     * @param companyMaster the value for company_information.company_master
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyMaster(String companyMaster) {
        this.companyMaster = companyMaster == null ? null : companyMaster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_keyword
     *
     * @return the value of company_information.company_keyword
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyKeyword() {
        return companyKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_keyword
     *
     * @param companyKeyword the value for company_information.company_keyword
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyKeyword(String companyKeyword) {
        this.companyKeyword = companyKeyword == null ? null : companyKeyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_description
     *
     * @return the value of company_information.company_description
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyDescription() {
        return companyDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_description
     *
     * @param companyDescription the value for company_information.company_description
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyDescription(String companyDescription) {
        this.companyDescription = companyDescription == null ? null : companyDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_icp
     *
     * @return the value of company_information.company_icp
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyIcp() {
        return companyIcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_icp
     *
     * @param companyIcp the value for company_information.company_icp
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyIcp(String companyIcp) {
        this.companyIcp = companyIcp == null ? null : companyIcp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.ompany_latitude
     *
     * @return the value of company_information.ompany_latitude
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public BigDecimal getOmpanyLatitude() {
        return ompanyLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.ompany_latitude
     *
     * @param ompanyLatitude the value for company_information.ompany_latitude
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setOmpanyLatitude(BigDecimal ompanyLatitude) {
        this.ompanyLatitude = ompanyLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_longitude
     *
     * @return the value of company_information.company_longitude
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public BigDecimal getCompanyLongitude() {
        return companyLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_longitude
     *
     * @param companyLongitude the value for company_information.company_longitude
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyLongitude(BigDecimal companyLongitude) {
        this.companyLongitude = companyLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_information.company_wechat
     *
     * @return the value of company_information.company_wechat
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getCompanyWechat() {
        return companyWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_information.company_wechat
     *
     * @param companyWechat the value for company_information.company_wechat
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setCompanyWechat(String companyWechat) {
        this.companyWechat = companyWechat == null ? null : companyWechat.trim();
    }
}