package anonymous.developer.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CompanyInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public CompanyInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoIsNull() {
            addCriterion("company_logo is null");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoIsNotNull() {
            addCriterion("company_logo is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoEqualTo(String value) {
            addCriterion("company_logo =", value, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoNotEqualTo(String value) {
            addCriterion("company_logo <>", value, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoGreaterThan(String value) {
            addCriterion("company_logo >", value, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoGreaterThanOrEqualTo(String value) {
            addCriterion("company_logo >=", value, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoLessThan(String value) {
            addCriterion("company_logo <", value, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoLessThanOrEqualTo(String value) {
            addCriterion("company_logo <=", value, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoLike(String value) {
            addCriterion("company_logo like", value, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoNotLike(String value) {
            addCriterion("company_logo not like", value, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoIn(List<String> values) {
            addCriterion("company_logo in", values, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoNotIn(List<String> values) {
            addCriterion("company_logo not in", values, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoBetween(String value1, String value2) {
            addCriterion("company_logo between", value1, value2, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyLogoNotBetween(String value1, String value2) {
            addCriterion("company_logo not between", value1, value2, "companyLogo");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneIsNull() {
            addCriterion("company_contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneIsNotNull() {
            addCriterion("company_contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneEqualTo(String value) {
            addCriterion("company_contact_phone =", value, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneNotEqualTo(String value) {
            addCriterion("company_contact_phone <>", value, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneGreaterThan(String value) {
            addCriterion("company_contact_phone >", value, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("company_contact_phone >=", value, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneLessThan(String value) {
            addCriterion("company_contact_phone <", value, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("company_contact_phone <=", value, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneLike(String value) {
            addCriterion("company_contact_phone like", value, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneNotLike(String value) {
            addCriterion("company_contact_phone not like", value, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneIn(List<String> values) {
            addCriterion("company_contact_phone in", values, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneNotIn(List<String> values) {
            addCriterion("company_contact_phone not in", values, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneBetween(String value1, String value2) {
            addCriterion("company_contact_phone between", value1, value2, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactPhoneNotBetween(String value1, String value2) {
            addCriterion("company_contact_phone not between", value1, value2, "companyContactPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqIsNull() {
            addCriterion("company_contact_qq is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqIsNotNull() {
            addCriterion("company_contact_qq is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqEqualTo(String value) {
            addCriterion("company_contact_qq =", value, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqNotEqualTo(String value) {
            addCriterion("company_contact_qq <>", value, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqGreaterThan(String value) {
            addCriterion("company_contact_qq >", value, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqGreaterThanOrEqualTo(String value) {
            addCriterion("company_contact_qq >=", value, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqLessThan(String value) {
            addCriterion("company_contact_qq <", value, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqLessThanOrEqualTo(String value) {
            addCriterion("company_contact_qq <=", value, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqLike(String value) {
            addCriterion("company_contact_qq like", value, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqNotLike(String value) {
            addCriterion("company_contact_qq not like", value, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqIn(List<String> values) {
            addCriterion("company_contact_qq in", values, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqNotIn(List<String> values) {
            addCriterion("company_contact_qq not in", values, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqBetween(String value1, String value2) {
            addCriterion("company_contact_qq between", value1, value2, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyContactQqNotBetween(String value1, String value2) {
            addCriterion("company_contact_qq not between", value1, value2, "companyContactQq");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailIsNull() {
            addCriterion("company_email is null");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailIsNotNull() {
            addCriterion("company_email is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailEqualTo(String value) {
            addCriterion("company_email =", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailNotEqualTo(String value) {
            addCriterion("company_email <>", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailGreaterThan(String value) {
            addCriterion("company_email >", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailGreaterThanOrEqualTo(String value) {
            addCriterion("company_email >=", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailLessThan(String value) {
            addCriterion("company_email <", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailLessThanOrEqualTo(String value) {
            addCriterion("company_email <=", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailLike(String value) {
            addCriterion("company_email like", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailNotLike(String value) {
            addCriterion("company_email not like", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailIn(List<String> values) {
            addCriterion("company_email in", values, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailNotIn(List<String> values) {
            addCriterion("company_email not in", values, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailBetween(String value1, String value2) {
            addCriterion("company_email between", value1, value2, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailNotBetween(String value1, String value2) {
            addCriterion("company_email not between", value1, value2, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNull() {
            addCriterion("company_address is null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNotNull() {
            addCriterion("company_address is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressEqualTo(String value) {
            addCriterion("company_address =", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotEqualTo(String value) {
            addCriterion("company_address <>", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThan(String value) {
            addCriterion("company_address >", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("company_address >=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThan(String value) {
            addCriterion("company_address <", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThanOrEqualTo(String value) {
            addCriterion("company_address <=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLike(String value) {
            addCriterion("company_address like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotLike(String value) {
            addCriterion("company_address not like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIn(List<String> values) {
            addCriterion("company_address in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotIn(List<String> values) {
            addCriterion("company_address not in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressBetween(String value1, String value2) {
            addCriterion("company_address between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotBetween(String value1, String value2) {
            addCriterion("company_address not between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeIsNull() {
            addCriterion("company_qrcode is null");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeIsNotNull() {
            addCriterion("company_qrcode is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeEqualTo(String value) {
            addCriterion("company_qrcode =", value, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeNotEqualTo(String value) {
            addCriterion("company_qrcode <>", value, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeGreaterThan(String value) {
            addCriterion("company_qrcode >", value, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeGreaterThanOrEqualTo(String value) {
            addCriterion("company_qrcode >=", value, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeLessThan(String value) {
            addCriterion("company_qrcode <", value, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeLessThanOrEqualTo(String value) {
            addCriterion("company_qrcode <=", value, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeLike(String value) {
            addCriterion("company_qrcode like", value, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeNotLike(String value) {
            addCriterion("company_qrcode not like", value, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeIn(List<String> values) {
            addCriterion("company_qrcode in", values, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeNotIn(List<String> values) {
            addCriterion("company_qrcode not in", values, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeBetween(String value1, String value2) {
            addCriterion("company_qrcode between", value1, value2, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyQrcodeNotBetween(String value1, String value2) {
            addCriterion("company_qrcode not between", value1, value2, "companyQrcode");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterIsNull() {
            addCriterion("company_master is null");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterIsNotNull() {
            addCriterion("company_master is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterEqualTo(String value) {
            addCriterion("company_master =", value, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterNotEqualTo(String value) {
            addCriterion("company_master <>", value, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterGreaterThan(String value) {
            addCriterion("company_master >", value, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterGreaterThanOrEqualTo(String value) {
            addCriterion("company_master >=", value, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterLessThan(String value) {
            addCriterion("company_master <", value, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterLessThanOrEqualTo(String value) {
            addCriterion("company_master <=", value, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterLike(String value) {
            addCriterion("company_master like", value, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterNotLike(String value) {
            addCriterion("company_master not like", value, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterIn(List<String> values) {
            addCriterion("company_master in", values, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterNotIn(List<String> values) {
            addCriterion("company_master not in", values, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterBetween(String value1, String value2) {
            addCriterion("company_master between", value1, value2, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyMasterNotBetween(String value1, String value2) {
            addCriterion("company_master not between", value1, value2, "companyMaster");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordIsNull() {
            addCriterion("company_keyword is null");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordIsNotNull() {
            addCriterion("company_keyword is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordEqualTo(String value) {
            addCriterion("company_keyword =", value, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordNotEqualTo(String value) {
            addCriterion("company_keyword <>", value, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordGreaterThan(String value) {
            addCriterion("company_keyword >", value, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("company_keyword >=", value, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordLessThan(String value) {
            addCriterion("company_keyword <", value, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordLessThanOrEqualTo(String value) {
            addCriterion("company_keyword <=", value, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordLike(String value) {
            addCriterion("company_keyword like", value, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordNotLike(String value) {
            addCriterion("company_keyword not like", value, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordIn(List<String> values) {
            addCriterion("company_keyword in", values, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordNotIn(List<String> values) {
            addCriterion("company_keyword not in", values, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordBetween(String value1, String value2) {
            addCriterion("company_keyword between", value1, value2, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyKeywordNotBetween(String value1, String value2) {
            addCriterion("company_keyword not between", value1, value2, "companyKeyword");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionIsNull() {
            addCriterion("company_description is null");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionIsNotNull() {
            addCriterion("company_description is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionEqualTo(String value) {
            addCriterion("company_description =", value, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionNotEqualTo(String value) {
            addCriterion("company_description <>", value, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionGreaterThan(String value) {
            addCriterion("company_description >", value, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("company_description >=", value, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionLessThan(String value) {
            addCriterion("company_description <", value, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionLessThanOrEqualTo(String value) {
            addCriterion("company_description <=", value, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionLike(String value) {
            addCriterion("company_description like", value, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionNotLike(String value) {
            addCriterion("company_description not like", value, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionIn(List<String> values) {
            addCriterion("company_description in", values, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionNotIn(List<String> values) {
            addCriterion("company_description not in", values, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionBetween(String value1, String value2) {
            addCriterion("company_description between", value1, value2, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyDescriptionNotBetween(String value1, String value2) {
            addCriterion("company_description not between", value1, value2, "companyDescription");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpIsNull() {
            addCriterion("company_icp is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpIsNotNull() {
            addCriterion("company_icp is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpEqualTo(String value) {
            addCriterion("company_icp =", value, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpNotEqualTo(String value) {
            addCriterion("company_icp <>", value, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpGreaterThan(String value) {
            addCriterion("company_icp >", value, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpGreaterThanOrEqualTo(String value) {
            addCriterion("company_icp >=", value, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpLessThan(String value) {
            addCriterion("company_icp <", value, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpLessThanOrEqualTo(String value) {
            addCriterion("company_icp <=", value, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpLike(String value) {
            addCriterion("company_icp like", value, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpNotLike(String value) {
            addCriterion("company_icp not like", value, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpIn(List<String> values) {
            addCriterion("company_icp in", values, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpNotIn(List<String> values) {
            addCriterion("company_icp not in", values, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpBetween(String value1, String value2) {
            addCriterion("company_icp between", value1, value2, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andCompanyIcpNotBetween(String value1, String value2) {
            addCriterion("company_icp not between", value1, value2, "companyIcp");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeIsNull() {
            addCriterion("ompany_latitude is null");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeIsNotNull() {
            addCriterion("ompany_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeEqualTo(BigDecimal value) {
            addCriterion("ompany_latitude =", value, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("ompany_latitude <>", value, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeGreaterThan(BigDecimal value) {
            addCriterion("ompany_latitude >", value, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ompany_latitude >=", value, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeLessThan(BigDecimal value) {
            addCriterion("ompany_latitude <", value, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ompany_latitude <=", value, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeIn(List<BigDecimal> values) {
            addCriterion("ompany_latitude in", values, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("ompany_latitude not in", values, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ompany_latitude between", value1, value2, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andOmpanyLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ompany_latitude not between", value1, value2, "ompanyLatitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeIsNull() {
            addCriterion("company_longitude is null");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeIsNotNull() {
            addCriterion("company_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeEqualTo(BigDecimal value) {
            addCriterion("company_longitude =", value, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeNotEqualTo(BigDecimal value) {
            addCriterion("company_longitude <>", value, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeGreaterThan(BigDecimal value) {
            addCriterion("company_longitude >", value, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("company_longitude >=", value, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeLessThan(BigDecimal value) {
            addCriterion("company_longitude <", value, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("company_longitude <=", value, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeIn(List<BigDecimal> values) {
            addCriterion("company_longitude in", values, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeNotIn(List<BigDecimal> values) {
            addCriterion("company_longitude not in", values, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("company_longitude between", value1, value2, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("company_longitude not between", value1, value2, "companyLongitude");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatIsNull() {
            addCriterion("company_wechat is null");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatIsNotNull() {
            addCriterion("company_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatEqualTo(String value) {
            addCriterion("company_wechat =", value, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatNotEqualTo(String value) {
            addCriterion("company_wechat <>", value, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatGreaterThan(String value) {
            addCriterion("company_wechat >", value, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatGreaterThanOrEqualTo(String value) {
            addCriterion("company_wechat >=", value, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatLessThan(String value) {
            addCriterion("company_wechat <", value, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatLessThanOrEqualTo(String value) {
            addCriterion("company_wechat <=", value, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatLike(String value) {
            addCriterion("company_wechat like", value, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatNotLike(String value) {
            addCriterion("company_wechat not like", value, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatIn(List<String> values) {
            addCriterion("company_wechat in", values, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatNotIn(List<String> values) {
            addCriterion("company_wechat not in", values, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatBetween(String value1, String value2) {
            addCriterion("company_wechat between", value1, value2, "companyWechat");
            return (Criteria) this;
        }

        public Criteria andCompanyWechatNotBetween(String value1, String value2) {
            addCriterion("company_wechat not between", value1, value2, "companyWechat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_information
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 15 02:52:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_information
     *
     * @mbg.generated Sat Jun 15 02:52:49 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}