package anonymous.developer.model;

import java.util.ArrayList;
import java.util.List;

public class NavigationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public NavigationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNavigationIdIsNull() {
            addCriterion("navigation_id is null");
            return (Criteria) this;
        }

        public Criteria andNavigationIdIsNotNull() {
            addCriterion("navigation_id is not null");
            return (Criteria) this;
        }

        public Criteria andNavigationIdEqualTo(Integer value) {
            addCriterion("navigation_id =", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdNotEqualTo(Integer value) {
            addCriterion("navigation_id <>", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdGreaterThan(Integer value) {
            addCriterion("navigation_id >", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("navigation_id >=", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdLessThan(Integer value) {
            addCriterion("navigation_id <", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdLessThanOrEqualTo(Integer value) {
            addCriterion("navigation_id <=", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdIn(List<Integer> values) {
            addCriterion("navigation_id in", values, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdNotIn(List<Integer> values) {
            addCriterion("navigation_id not in", values, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdBetween(Integer value1, Integer value2) {
            addCriterion("navigation_id between", value1, value2, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("navigation_id not between", value1, value2, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationNameIsNull() {
            addCriterion("navigation_name is null");
            return (Criteria) this;
        }

        public Criteria andNavigationNameIsNotNull() {
            addCriterion("navigation_name is not null");
            return (Criteria) this;
        }

        public Criteria andNavigationNameEqualTo(String value) {
            addCriterion("navigation_name =", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameNotEqualTo(String value) {
            addCriterion("navigation_name <>", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameGreaterThan(String value) {
            addCriterion("navigation_name >", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameGreaterThanOrEqualTo(String value) {
            addCriterion("navigation_name >=", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameLessThan(String value) {
            addCriterion("navigation_name <", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameLessThanOrEqualTo(String value) {
            addCriterion("navigation_name <=", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameLike(String value) {
            addCriterion("navigation_name like", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameNotLike(String value) {
            addCriterion("navigation_name not like", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameIn(List<String> values) {
            addCriterion("navigation_name in", values, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameNotIn(List<String> values) {
            addCriterion("navigation_name not in", values, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameBetween(String value1, String value2) {
            addCriterion("navigation_name between", value1, value2, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameNotBetween(String value1, String value2) {
            addCriterion("navigation_name not between", value1, value2, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlIsNull() {
            addCriterion("navigation_url is null");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlIsNotNull() {
            addCriterion("navigation_url is not null");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlEqualTo(String value) {
            addCriterion("navigation_url =", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlNotEqualTo(String value) {
            addCriterion("navigation_url <>", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlGreaterThan(String value) {
            addCriterion("navigation_url >", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlGreaterThanOrEqualTo(String value) {
            addCriterion("navigation_url >=", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlLessThan(String value) {
            addCriterion("navigation_url <", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlLessThanOrEqualTo(String value) {
            addCriterion("navigation_url <=", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlLike(String value) {
            addCriterion("navigation_url like", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlNotLike(String value) {
            addCriterion("navigation_url not like", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlIn(List<String> values) {
            addCriterion("navigation_url in", values, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlNotIn(List<String> values) {
            addCriterion("navigation_url not in", values, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlBetween(String value1, String value2) {
            addCriterion("navigation_url between", value1, value2, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlNotBetween(String value1, String value2) {
            addCriterion("navigation_url not between", value1, value2, "navigationUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table navigation
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 15 02:53:53 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table navigation
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}