package anonymous.developer.model;

public class Navigation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation.navigation_id
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    private Integer navigationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation.navigation_name
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    private String navigationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation.navigation_url
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    private String navigationUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation.navigation_id
     *
     * @return the value of navigation.navigation_id
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public Integer getNavigationId() {
        return navigationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation.navigation_id
     *
     * @param navigationId the value for navigation.navigation_id
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public void setNavigationId(Integer navigationId) {
        this.navigationId = navigationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation.navigation_name
     *
     * @return the value of navigation.navigation_name
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public String getNavigationName() {
        return navigationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation.navigation_name
     *
     * @param navigationName the value for navigation.navigation_name
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public void setNavigationName(String navigationName) {
        this.navigationName = navigationName == null ? null : navigationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation.navigation_url
     *
     * @return the value of navigation.navigation_url
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public String getNavigationUrl() {
        return navigationUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation.navigation_url
     *
     * @param navigationUrl the value for navigation.navigation_url
     *
     * @mbg.generated Sat Jun 15 02:53:53 CST 2019
     */
    public void setNavigationUrl(String navigationUrl) {
        this.navigationUrl = navigationUrl == null ? null : navigationUrl.trim();
    }
}