package anonymous.developer.model;

public class NewsClassification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_classification.news_classification_id
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    private Integer newsClassificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_classification.news_classification_name
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    private String newsClassificationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_classification.news_classification_id
     *
     * @return the value of news_classification.news_classification_id
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public Integer getNewsClassificationId() {
        return newsClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_classification.news_classification_id
     *
     * @param newsClassificationId the value for news_classification.news_classification_id
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public void setNewsClassificationId(Integer newsClassificationId) {
        this.newsClassificationId = newsClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_classification.news_classification_name
     *
     * @return the value of news_classification.news_classification_name
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public String getNewsClassificationName() {
        return newsClassificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_classification.news_classification_name
     *
     * @param newsClassificationName the value for news_classification.news_classification_name
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public void setNewsClassificationName(String newsClassificationName) {
        this.newsClassificationName = newsClassificationName == null ? null : newsClassificationName.trim();
    }
}