package anonymous.developer.model;

import java.util.ArrayList;
import java.util.List;

public class NewsCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public NewsCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNewsCommentIdIsNull() {
            addCriterion("news_comment_id is null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdIsNotNull() {
            addCriterion("news_comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdEqualTo(Integer value) {
            addCriterion("news_comment_id =", value, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdNotEqualTo(Integer value) {
            addCriterion("news_comment_id <>", value, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdGreaterThan(Integer value) {
            addCriterion("news_comment_id >", value, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_comment_id >=", value, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdLessThan(Integer value) {
            addCriterion("news_comment_id <", value, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdLessThanOrEqualTo(Integer value) {
            addCriterion("news_comment_id <=", value, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdIn(List<Integer> values) {
            addCriterion("news_comment_id in", values, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdNotIn(List<Integer> values) {
            addCriterion("news_comment_id not in", values, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdBetween(Integer value1, Integer value2) {
            addCriterion("news_comment_id between", value1, value2, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("news_comment_id not between", value1, value2, "newsCommentId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameIsNull() {
            addCriterion("news_comment_name is null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameIsNotNull() {
            addCriterion("news_comment_name is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameEqualTo(String value) {
            addCriterion("news_comment_name =", value, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameNotEqualTo(String value) {
            addCriterion("news_comment_name <>", value, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameGreaterThan(String value) {
            addCriterion("news_comment_name >", value, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameGreaterThanOrEqualTo(String value) {
            addCriterion("news_comment_name >=", value, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameLessThan(String value) {
            addCriterion("news_comment_name <", value, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameLessThanOrEqualTo(String value) {
            addCriterion("news_comment_name <=", value, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameLike(String value) {
            addCriterion("news_comment_name like", value, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameNotLike(String value) {
            addCriterion("news_comment_name not like", value, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameIn(List<String> values) {
            addCriterion("news_comment_name in", values, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameNotIn(List<String> values) {
            addCriterion("news_comment_name not in", values, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameBetween(String value1, String value2) {
            addCriterion("news_comment_name between", value1, value2, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentNameNotBetween(String value1, String value2) {
            addCriterion("news_comment_name not between", value1, value2, "newsCommentName");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlIsNull() {
            addCriterion("news_comment_picture_url is null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlIsNotNull() {
            addCriterion("news_comment_picture_url is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlEqualTo(String value) {
            addCriterion("news_comment_picture_url =", value, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlNotEqualTo(String value) {
            addCriterion("news_comment_picture_url <>", value, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlGreaterThan(String value) {
            addCriterion("news_comment_picture_url >", value, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlGreaterThanOrEqualTo(String value) {
            addCriterion("news_comment_picture_url >=", value, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlLessThan(String value) {
            addCriterion("news_comment_picture_url <", value, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlLessThanOrEqualTo(String value) {
            addCriterion("news_comment_picture_url <=", value, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlLike(String value) {
            addCriterion("news_comment_picture_url like", value, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlNotLike(String value) {
            addCriterion("news_comment_picture_url not like", value, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlIn(List<String> values) {
            addCriterion("news_comment_picture_url in", values, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlNotIn(List<String> values) {
            addCriterion("news_comment_picture_url not in", values, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlBetween(String value1, String value2) {
            addCriterion("news_comment_picture_url between", value1, value2, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentPictureUrlNotBetween(String value1, String value2) {
            addCriterion("news_comment_picture_url not between", value1, value2, "newsCommentPictureUrl");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailIsNull() {
            addCriterion("news_comment_email is null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailIsNotNull() {
            addCriterion("news_comment_email is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailEqualTo(String value) {
            addCriterion("news_comment_email =", value, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailNotEqualTo(String value) {
            addCriterion("news_comment_email <>", value, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailGreaterThan(String value) {
            addCriterion("news_comment_email >", value, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailGreaterThanOrEqualTo(String value) {
            addCriterion("news_comment_email >=", value, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailLessThan(String value) {
            addCriterion("news_comment_email <", value, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailLessThanOrEqualTo(String value) {
            addCriterion("news_comment_email <=", value, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailLike(String value) {
            addCriterion("news_comment_email like", value, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailNotLike(String value) {
            addCriterion("news_comment_email not like", value, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailIn(List<String> values) {
            addCriterion("news_comment_email in", values, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailNotIn(List<String> values) {
            addCriterion("news_comment_email not in", values, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailBetween(String value1, String value2) {
            addCriterion("news_comment_email between", value1, value2, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentEmailNotBetween(String value1, String value2) {
            addCriterion("news_comment_email not between", value1, value2, "newsCommentEmail");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectIsNull() {
            addCriterion("news_comment_subject is null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectIsNotNull() {
            addCriterion("news_comment_subject is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectEqualTo(String value) {
            addCriterion("news_comment_subject =", value, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectNotEqualTo(String value) {
            addCriterion("news_comment_subject <>", value, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectGreaterThan(String value) {
            addCriterion("news_comment_subject >", value, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("news_comment_subject >=", value, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectLessThan(String value) {
            addCriterion("news_comment_subject <", value, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectLessThanOrEqualTo(String value) {
            addCriterion("news_comment_subject <=", value, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectLike(String value) {
            addCriterion("news_comment_subject like", value, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectNotLike(String value) {
            addCriterion("news_comment_subject not like", value, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectIn(List<String> values) {
            addCriterion("news_comment_subject in", values, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectNotIn(List<String> values) {
            addCriterion("news_comment_subject not in", values, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectBetween(String value1, String value2) {
            addCriterion("news_comment_subject between", value1, value2, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentSubjectNotBetween(String value1, String value2) {
            addCriterion("news_comment_subject not between", value1, value2, "newsCommentSubject");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentIsNull() {
            addCriterion("news_comment_content is null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentIsNotNull() {
            addCriterion("news_comment_content is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentEqualTo(String value) {
            addCriterion("news_comment_content =", value, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentNotEqualTo(String value) {
            addCriterion("news_comment_content <>", value, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentGreaterThan(String value) {
            addCriterion("news_comment_content >", value, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentGreaterThanOrEqualTo(String value) {
            addCriterion("news_comment_content >=", value, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentLessThan(String value) {
            addCriterion("news_comment_content <", value, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentLessThanOrEqualTo(String value) {
            addCriterion("news_comment_content <=", value, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentLike(String value) {
            addCriterion("news_comment_content like", value, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentNotLike(String value) {
            addCriterion("news_comment_content not like", value, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentIn(List<String> values) {
            addCriterion("news_comment_content in", values, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentNotIn(List<String> values) {
            addCriterion("news_comment_content not in", values, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentBetween(String value1, String value2) {
            addCriterion("news_comment_content between", value1, value2, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentContentNotBetween(String value1, String value2) {
            addCriterion("news_comment_content not between", value1, value2, "newsCommentContent");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdIsNull() {
            addCriterion("news_comment_reply_id is null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdIsNotNull() {
            addCriterion("news_comment_reply_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdEqualTo(Integer value) {
            addCriterion("news_comment_reply_id =", value, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdNotEqualTo(Integer value) {
            addCriterion("news_comment_reply_id <>", value, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdGreaterThan(Integer value) {
            addCriterion("news_comment_reply_id >", value, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_comment_reply_id >=", value, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdLessThan(Integer value) {
            addCriterion("news_comment_reply_id <", value, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdLessThanOrEqualTo(Integer value) {
            addCriterion("news_comment_reply_id <=", value, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdIn(List<Integer> values) {
            addCriterion("news_comment_reply_id in", values, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdNotIn(List<Integer> values) {
            addCriterion("news_comment_reply_id not in", values, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdBetween(Integer value1, Integer value2) {
            addCriterion("news_comment_reply_id between", value1, value2, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsCommentReplyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("news_comment_reply_id not between", value1, value2, "newsCommentReplyId");
            return (Criteria) this;
        }

        public Criteria andNewsIdIsNull() {
            addCriterion("news_id is null");
            return (Criteria) this;
        }

        public Criteria andNewsIdIsNotNull() {
            addCriterion("news_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewsIdEqualTo(Integer value) {
            addCriterion("news_id =", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotEqualTo(Integer value) {
            addCriterion("news_id <>", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdGreaterThan(Integer value) {
            addCriterion("news_id >", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_id >=", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdLessThan(Integer value) {
            addCriterion("news_id <", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdLessThanOrEqualTo(Integer value) {
            addCriterion("news_id <=", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdIn(List<Integer> values) {
            addCriterion("news_id in", values, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotIn(List<Integer> values) {
            addCriterion("news_id not in", values, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdBetween(Integer value1, Integer value2) {
            addCriterion("news_id between", value1, value2, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("news_id not between", value1, value2, "newsId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_comment
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 15 02:57:41 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_comment
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}