package anonymous.developer.model;

public class NewsComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_comment_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    private Integer newsCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_comment_name
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    private String newsCommentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_comment_picture_url
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    private String newsCommentPictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_comment_email
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    private String newsCommentEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_comment_subject
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    private String newsCommentSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_comment_content
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    private String newsCommentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_comment_reply_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    private Integer newsCommentReplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    private Integer newsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_comment_id
     *
     * @return the value of news_comment.news_comment_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public Integer getNewsCommentId() {
        return newsCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_comment_id
     *
     * @param newsCommentId the value for news_comment.news_comment_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setNewsCommentId(Integer newsCommentId) {
        this.newsCommentId = newsCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_comment_name
     *
     * @return the value of news_comment.news_comment_name
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public String getNewsCommentName() {
        return newsCommentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_comment_name
     *
     * @param newsCommentName the value for news_comment.news_comment_name
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setNewsCommentName(String newsCommentName) {
        this.newsCommentName = newsCommentName == null ? null : newsCommentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_comment_picture_url
     *
     * @return the value of news_comment.news_comment_picture_url
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public String getNewsCommentPictureUrl() {
        return newsCommentPictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_comment_picture_url
     *
     * @param newsCommentPictureUrl the value for news_comment.news_comment_picture_url
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setNewsCommentPictureUrl(String newsCommentPictureUrl) {
        this.newsCommentPictureUrl = newsCommentPictureUrl == null ? null : newsCommentPictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_comment_email
     *
     * @return the value of news_comment.news_comment_email
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public String getNewsCommentEmail() {
        return newsCommentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_comment_email
     *
     * @param newsCommentEmail the value for news_comment.news_comment_email
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setNewsCommentEmail(String newsCommentEmail) {
        this.newsCommentEmail = newsCommentEmail == null ? null : newsCommentEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_comment_subject
     *
     * @return the value of news_comment.news_comment_subject
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public String getNewsCommentSubject() {
        return newsCommentSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_comment_subject
     *
     * @param newsCommentSubject the value for news_comment.news_comment_subject
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setNewsCommentSubject(String newsCommentSubject) {
        this.newsCommentSubject = newsCommentSubject == null ? null : newsCommentSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_comment_content
     *
     * @return the value of news_comment.news_comment_content
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public String getNewsCommentContent() {
        return newsCommentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_comment_content
     *
     * @param newsCommentContent the value for news_comment.news_comment_content
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setNewsCommentContent(String newsCommentContent) {
        this.newsCommentContent = newsCommentContent == null ? null : newsCommentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_comment_reply_id
     *
     * @return the value of news_comment.news_comment_reply_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public Integer getNewsCommentReplyId() {
        return newsCommentReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_comment_reply_id
     *
     * @param newsCommentReplyId the value for news_comment.news_comment_reply_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setNewsCommentReplyId(Integer newsCommentReplyId) {
        this.newsCommentReplyId = newsCommentReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_id
     *
     * @return the value of news_comment.news_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_id
     *
     * @param newsId the value for news_comment.news_id
     *
     * @mbg.generated Sat Jun 15 02:57:41 CST 2019
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }
}