package anonymous.developer.model;

import java.util.ArrayList;
import java.util.List;

public class NewsClassificationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public NewsClassificationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNewsClassificationIdIsNull() {
            addCriterion("news_classification_id is null");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdIsNotNull() {
            addCriterion("news_classification_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdEqualTo(Integer value) {
            addCriterion("news_classification_id =", value, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdNotEqualTo(Integer value) {
            addCriterion("news_classification_id <>", value, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdGreaterThan(Integer value) {
            addCriterion("news_classification_id >", value, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_classification_id >=", value, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdLessThan(Integer value) {
            addCriterion("news_classification_id <", value, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdLessThanOrEqualTo(Integer value) {
            addCriterion("news_classification_id <=", value, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdIn(List<Integer> values) {
            addCriterion("news_classification_id in", values, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdNotIn(List<Integer> values) {
            addCriterion("news_classification_id not in", values, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdBetween(Integer value1, Integer value2) {
            addCriterion("news_classification_id between", value1, value2, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("news_classification_id not between", value1, value2, "newsClassificationId");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameIsNull() {
            addCriterion("news_classification_name is null");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameIsNotNull() {
            addCriterion("news_classification_name is not null");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameEqualTo(String value) {
            addCriterion("news_classification_name =", value, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameNotEqualTo(String value) {
            addCriterion("news_classification_name <>", value, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameGreaterThan(String value) {
            addCriterion("news_classification_name >", value, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameGreaterThanOrEqualTo(String value) {
            addCriterion("news_classification_name >=", value, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameLessThan(String value) {
            addCriterion("news_classification_name <", value, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameLessThanOrEqualTo(String value) {
            addCriterion("news_classification_name <=", value, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameLike(String value) {
            addCriterion("news_classification_name like", value, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameNotLike(String value) {
            addCriterion("news_classification_name not like", value, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameIn(List<String> values) {
            addCriterion("news_classification_name in", values, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameNotIn(List<String> values) {
            addCriterion("news_classification_name not in", values, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameBetween(String value1, String value2) {
            addCriterion("news_classification_name between", value1, value2, "newsClassificationName");
            return (Criteria) this;
        }

        public Criteria andNewsClassificationNameNotBetween(String value1, String value2) {
            addCriterion("news_classification_name not between", value1, value2, "newsClassificationName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_classification
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 15 02:55:11 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_classification
     *
     * @mbg.generated Sat Jun 15 02:55:11 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}