package anonymous.developer.model;

import java.util.Date;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_id
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_name
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_description
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    private String permissionDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_url
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    private String permissionUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_parent
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    private Integer permissionParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_type
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    private Byte permissionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_create_datetime
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    private Date permissionCreateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_update_datetime
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    private Date permissionUpdateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_id
     *
     * @return the value of permission.permission_id
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_id
     *
     * @param permissionId the value for permission.permission_id
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_name
     *
     * @return the value of permission.permission_name
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_name
     *
     * @param permissionName the value for permission.permission_name
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_description
     *
     * @return the value of permission.permission_description
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public String getPermissionDescription() {
        return permissionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_description
     *
     * @param permissionDescription the value for permission.permission_description
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription == null ? null : permissionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_url
     *
     * @return the value of permission.permission_url
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_url
     *
     * @param permissionUrl the value for permission.permission_url
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_parent
     *
     * @return the value of permission.permission_parent
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public Integer getPermissionParent() {
        return permissionParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_parent
     *
     * @param permissionParent the value for permission.permission_parent
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setPermissionParent(Integer permissionParent) {
        this.permissionParent = permissionParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_type
     *
     * @return the value of permission.permission_type
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public Byte getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_type
     *
     * @param permissionType the value for permission.permission_type
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setPermissionType(Byte permissionType) {
        this.permissionType = permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_create_datetime
     *
     * @return the value of permission.permission_create_datetime
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public Date getPermissionCreateDatetime() {
        return permissionCreateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_create_datetime
     *
     * @param permissionCreateDatetime the value for permission.permission_create_datetime
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setPermissionCreateDatetime(Date permissionCreateDatetime) {
        this.permissionCreateDatetime = permissionCreateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_update_datetime
     *
     * @return the value of permission.permission_update_datetime
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public Date getPermissionUpdateDatetime() {
        return permissionUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_update_datetime
     *
     * @param permissionUpdateDatetime the value for permission.permission_update_datetime
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setPermissionUpdateDatetime(Date permissionUpdateDatetime) {
        this.permissionUpdateDatetime = permissionUpdateDatetime;
    }
}