package anonymous.developer.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PermissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public PermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPermissionIdIsNull() {
            addCriterion("permission_id is null");
            return (Criteria) this;
        }

        public Criteria andPermissionIdIsNotNull() {
            addCriterion("permission_id is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionIdEqualTo(Integer value) {
            addCriterion("permission_id =", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdNotEqualTo(Integer value) {
            addCriterion("permission_id <>", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdGreaterThan(Integer value) {
            addCriterion("permission_id >", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("permission_id >=", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdLessThan(Integer value) {
            addCriterion("permission_id <", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdLessThanOrEqualTo(Integer value) {
            addCriterion("permission_id <=", value, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdIn(List<Integer> values) {
            addCriterion("permission_id in", values, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdNotIn(List<Integer> values) {
            addCriterion("permission_id not in", values, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdBetween(Integer value1, Integer value2) {
            addCriterion("permission_id between", value1, value2, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("permission_id not between", value1, value2, "permissionId");
            return (Criteria) this;
        }

        public Criteria andPermissionNameIsNull() {
            addCriterion("permission_name is null");
            return (Criteria) this;
        }

        public Criteria andPermissionNameIsNotNull() {
            addCriterion("permission_name is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionNameEqualTo(String value) {
            addCriterion("permission_name =", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameNotEqualTo(String value) {
            addCriterion("permission_name <>", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameGreaterThan(String value) {
            addCriterion("permission_name >", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameGreaterThanOrEqualTo(String value) {
            addCriterion("permission_name >=", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameLessThan(String value) {
            addCriterion("permission_name <", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameLessThanOrEqualTo(String value) {
            addCriterion("permission_name <=", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameLike(String value) {
            addCriterion("permission_name like", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameNotLike(String value) {
            addCriterion("permission_name not like", value, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameIn(List<String> values) {
            addCriterion("permission_name in", values, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameNotIn(List<String> values) {
            addCriterion("permission_name not in", values, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameBetween(String value1, String value2) {
            addCriterion("permission_name between", value1, value2, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionNameNotBetween(String value1, String value2) {
            addCriterion("permission_name not between", value1, value2, "permissionName");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionIsNull() {
            addCriterion("permission_description is null");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionIsNotNull() {
            addCriterion("permission_description is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionEqualTo(String value) {
            addCriterion("permission_description =", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionNotEqualTo(String value) {
            addCriterion("permission_description <>", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionGreaterThan(String value) {
            addCriterion("permission_description >", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("permission_description >=", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionLessThan(String value) {
            addCriterion("permission_description <", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionLessThanOrEqualTo(String value) {
            addCriterion("permission_description <=", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionLike(String value) {
            addCriterion("permission_description like", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionNotLike(String value) {
            addCriterion("permission_description not like", value, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionIn(List<String> values) {
            addCriterion("permission_description in", values, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionNotIn(List<String> values) {
            addCriterion("permission_description not in", values, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionBetween(String value1, String value2) {
            addCriterion("permission_description between", value1, value2, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionDescriptionNotBetween(String value1, String value2) {
            addCriterion("permission_description not between", value1, value2, "permissionDescription");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlIsNull() {
            addCriterion("permission_url is null");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlIsNotNull() {
            addCriterion("permission_url is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlEqualTo(String value) {
            addCriterion("permission_url =", value, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlNotEqualTo(String value) {
            addCriterion("permission_url <>", value, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlGreaterThan(String value) {
            addCriterion("permission_url >", value, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlGreaterThanOrEqualTo(String value) {
            addCriterion("permission_url >=", value, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlLessThan(String value) {
            addCriterion("permission_url <", value, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlLessThanOrEqualTo(String value) {
            addCriterion("permission_url <=", value, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlLike(String value) {
            addCriterion("permission_url like", value, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlNotLike(String value) {
            addCriterion("permission_url not like", value, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlIn(List<String> values) {
            addCriterion("permission_url in", values, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlNotIn(List<String> values) {
            addCriterion("permission_url not in", values, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlBetween(String value1, String value2) {
            addCriterion("permission_url between", value1, value2, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionUrlNotBetween(String value1, String value2) {
            addCriterion("permission_url not between", value1, value2, "permissionUrl");
            return (Criteria) this;
        }

        public Criteria andPermissionParentIsNull() {
            addCriterion("permission_parent is null");
            return (Criteria) this;
        }

        public Criteria andPermissionParentIsNotNull() {
            addCriterion("permission_parent is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionParentEqualTo(Integer value) {
            addCriterion("permission_parent =", value, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentNotEqualTo(Integer value) {
            addCriterion("permission_parent <>", value, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentGreaterThan(Integer value) {
            addCriterion("permission_parent >", value, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentGreaterThanOrEqualTo(Integer value) {
            addCriterion("permission_parent >=", value, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentLessThan(Integer value) {
            addCriterion("permission_parent <", value, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentLessThanOrEqualTo(Integer value) {
            addCriterion("permission_parent <=", value, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentIn(List<Integer> values) {
            addCriterion("permission_parent in", values, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentNotIn(List<Integer> values) {
            addCriterion("permission_parent not in", values, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentBetween(Integer value1, Integer value2) {
            addCriterion("permission_parent between", value1, value2, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionParentNotBetween(Integer value1, Integer value2) {
            addCriterion("permission_parent not between", value1, value2, "permissionParent");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIsNull() {
            addCriterion("permission_type is null");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIsNotNull() {
            addCriterion("permission_type is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeEqualTo(Byte value) {
            addCriterion("permission_type =", value, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeNotEqualTo(Byte value) {
            addCriterion("permission_type <>", value, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeGreaterThan(Byte value) {
            addCriterion("permission_type >", value, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("permission_type >=", value, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeLessThan(Byte value) {
            addCriterion("permission_type <", value, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeLessThanOrEqualTo(Byte value) {
            addCriterion("permission_type <=", value, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeIn(List<Byte> values) {
            addCriterion("permission_type in", values, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeNotIn(List<Byte> values) {
            addCriterion("permission_type not in", values, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeBetween(Byte value1, Byte value2) {
            addCriterion("permission_type between", value1, value2, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("permission_type not between", value1, value2, "permissionType");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeIsNull() {
            addCriterion("permission_create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeIsNotNull() {
            addCriterion("permission_create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeEqualTo(Date value) {
            addCriterion("permission_create_datetime =", value, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeNotEqualTo(Date value) {
            addCriterion("permission_create_datetime <>", value, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeGreaterThan(Date value) {
            addCriterion("permission_create_datetime >", value, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("permission_create_datetime >=", value, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeLessThan(Date value) {
            addCriterion("permission_create_datetime <", value, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("permission_create_datetime <=", value, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeIn(List<Date> values) {
            addCriterion("permission_create_datetime in", values, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeNotIn(List<Date> values) {
            addCriterion("permission_create_datetime not in", values, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeBetween(Date value1, Date value2) {
            addCriterion("permission_create_datetime between", value1, value2, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionCreateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("permission_create_datetime not between", value1, value2, "permissionCreateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeIsNull() {
            addCriterion("permission_update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeIsNotNull() {
            addCriterion("permission_update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeEqualTo(Date value) {
            addCriterion("permission_update_datetime =", value, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeNotEqualTo(Date value) {
            addCriterion("permission_update_datetime <>", value, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeGreaterThan(Date value) {
            addCriterion("permission_update_datetime >", value, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("permission_update_datetime >=", value, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeLessThan(Date value) {
            addCriterion("permission_update_datetime <", value, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("permission_update_datetime <=", value, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeIn(List<Date> values) {
            addCriterion("permission_update_datetime in", values, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeNotIn(List<Date> values) {
            addCriterion("permission_update_datetime not in", values, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeBetween(Date value1, Date value2) {
            addCriterion("permission_update_datetime between", value1, value2, "permissionUpdateDatetime");
            return (Criteria) this;
        }

        public Criteria andPermissionUpdateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("permission_update_datetime not between", value1, value2, "permissionUpdateDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permission
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 15 02:59:40 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permission
     *
     * @mbg.generated Sat Jun 15 02:59:40 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}