package anonymous.developer.model;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_description
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    private String roleDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_create_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    private Date roleCreateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_update_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    private Date roleUpdateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_description
     *
     * @return the value of role.role_description
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_description
     *
     * @param roleDescription the value for role.role_description
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_create_datetime
     *
     * @return the value of role.role_create_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public Date getRoleCreateDatetime() {
        return roleCreateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_create_datetime
     *
     * @param roleCreateDatetime the value for role.role_create_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public void setRoleCreateDatetime(Date roleCreateDatetime) {
        this.roleCreateDatetime = roleCreateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_update_datetime
     *
     * @return the value of role.role_update_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public Date getRoleUpdateDatetime() {
        return roleUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_update_datetime
     *
     * @param roleUpdateDatetime the value for role.role_update_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:05 CST 2019
     */
    public void setRoleUpdateDatetime(Date roleUpdateDatetime) {
        this.roleUpdateDatetime = roleUpdateDatetime;
    }
}