package anonymous.developer.model;

public class SystemInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_information.system_id
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    private Integer systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_information.system_name
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    private String systemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_information.system_logo
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    private String systemLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_information.system_developer
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    private String systemDeveloper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_information.system_qrcode
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    private String systemQrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_information.system_copyright
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    private String systemCopyright;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_information.systeam_external_js
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    private String systeamExternalJs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_information.system_id
     *
     * @return the value of system_information.system_id
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_information.system_id
     *
     * @param systemId the value for system_information.system_id
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_information.system_name
     *
     * @return the value of system_information.system_name
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_information.system_name
     *
     * @param systemName the value for system_information.system_name
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_information.system_logo
     *
     * @return the value of system_information.system_logo
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public String getSystemLogo() {
        return systemLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_information.system_logo
     *
     * @param systemLogo the value for system_information.system_logo
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setSystemLogo(String systemLogo) {
        this.systemLogo = systemLogo == null ? null : systemLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_information.system_developer
     *
     * @return the value of system_information.system_developer
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public String getSystemDeveloper() {
        return systemDeveloper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_information.system_developer
     *
     * @param systemDeveloper the value for system_information.system_developer
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setSystemDeveloper(String systemDeveloper) {
        this.systemDeveloper = systemDeveloper == null ? null : systemDeveloper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_information.system_qrcode
     *
     * @return the value of system_information.system_qrcode
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public String getSystemQrcode() {
        return systemQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_information.system_qrcode
     *
     * @param systemQrcode the value for system_information.system_qrcode
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setSystemQrcode(String systemQrcode) {
        this.systemQrcode = systemQrcode == null ? null : systemQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_information.system_copyright
     *
     * @return the value of system_information.system_copyright
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public String getSystemCopyright() {
        return systemCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_information.system_copyright
     *
     * @param systemCopyright the value for system_information.system_copyright
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setSystemCopyright(String systemCopyright) {
        this.systemCopyright = systemCopyright == null ? null : systemCopyright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_information.systeam_external_js
     *
     * @return the value of system_information.systeam_external_js
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public String getSysteamExternalJs() {
        return systeamExternalJs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_information.systeam_external_js
     *
     * @param systeamExternalJs the value for system_information.systeam_external_js
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setSysteamExternalJs(String systeamExternalJs) {
        this.systeamExternalJs = systeamExternalJs == null ? null : systeamExternalJs.trim();
    }
}