package anonymous.developer.model;

import java.util.ArrayList;
import java.util.List;

public class SystemInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public SystemInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSystemIdIsNull() {
            addCriterion("system_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNotNull() {
            addCriterion("system_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemIdEqualTo(Integer value) {
            addCriterion("system_id =", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotEqualTo(Integer value) {
            addCriterion("system_id <>", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThan(Integer value) {
            addCriterion("system_id >", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_id >=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThan(Integer value) {
            addCriterion("system_id <", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThanOrEqualTo(Integer value) {
            addCriterion("system_id <=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdIn(List<Integer> values) {
            addCriterion("system_id in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotIn(List<Integer> values) {
            addCriterion("system_id not in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdBetween(Integer value1, Integer value2) {
            addCriterion("system_id between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("system_id not between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNull() {
            addCriterion("system_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNotNull() {
            addCriterion("system_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemNameEqualTo(String value) {
            addCriterion("system_name =", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotEqualTo(String value) {
            addCriterion("system_name <>", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThan(String value) {
            addCriterion("system_name >", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_name >=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThan(String value) {
            addCriterion("system_name <", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThanOrEqualTo(String value) {
            addCriterion("system_name <=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLike(String value) {
            addCriterion("system_name like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotLike(String value) {
            addCriterion("system_name not like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameIn(List<String> values) {
            addCriterion("system_name in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotIn(List<String> values) {
            addCriterion("system_name not in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameBetween(String value1, String value2) {
            addCriterion("system_name between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotBetween(String value1, String value2) {
            addCriterion("system_name not between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemLogoIsNull() {
            addCriterion("system_logo is null");
            return (Criteria) this;
        }

        public Criteria andSystemLogoIsNotNull() {
            addCriterion("system_logo is not null");
            return (Criteria) this;
        }

        public Criteria andSystemLogoEqualTo(String value) {
            addCriterion("system_logo =", value, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoNotEqualTo(String value) {
            addCriterion("system_logo <>", value, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoGreaterThan(String value) {
            addCriterion("system_logo >", value, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoGreaterThanOrEqualTo(String value) {
            addCriterion("system_logo >=", value, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoLessThan(String value) {
            addCriterion("system_logo <", value, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoLessThanOrEqualTo(String value) {
            addCriterion("system_logo <=", value, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoLike(String value) {
            addCriterion("system_logo like", value, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoNotLike(String value) {
            addCriterion("system_logo not like", value, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoIn(List<String> values) {
            addCriterion("system_logo in", values, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoNotIn(List<String> values) {
            addCriterion("system_logo not in", values, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoBetween(String value1, String value2) {
            addCriterion("system_logo between", value1, value2, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemLogoNotBetween(String value1, String value2) {
            addCriterion("system_logo not between", value1, value2, "systemLogo");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperIsNull() {
            addCriterion("system_developer is null");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperIsNotNull() {
            addCriterion("system_developer is not null");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperEqualTo(String value) {
            addCriterion("system_developer =", value, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperNotEqualTo(String value) {
            addCriterion("system_developer <>", value, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperGreaterThan(String value) {
            addCriterion("system_developer >", value, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperGreaterThanOrEqualTo(String value) {
            addCriterion("system_developer >=", value, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperLessThan(String value) {
            addCriterion("system_developer <", value, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperLessThanOrEqualTo(String value) {
            addCriterion("system_developer <=", value, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperLike(String value) {
            addCriterion("system_developer like", value, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperNotLike(String value) {
            addCriterion("system_developer not like", value, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperIn(List<String> values) {
            addCriterion("system_developer in", values, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperNotIn(List<String> values) {
            addCriterion("system_developer not in", values, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperBetween(String value1, String value2) {
            addCriterion("system_developer between", value1, value2, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemDeveloperNotBetween(String value1, String value2) {
            addCriterion("system_developer not between", value1, value2, "systemDeveloper");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeIsNull() {
            addCriterion("system_qrcode is null");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeIsNotNull() {
            addCriterion("system_qrcode is not null");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeEqualTo(String value) {
            addCriterion("system_qrcode =", value, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeNotEqualTo(String value) {
            addCriterion("system_qrcode <>", value, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeGreaterThan(String value) {
            addCriterion("system_qrcode >", value, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_qrcode >=", value, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeLessThan(String value) {
            addCriterion("system_qrcode <", value, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeLessThanOrEqualTo(String value) {
            addCriterion("system_qrcode <=", value, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeLike(String value) {
            addCriterion("system_qrcode like", value, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeNotLike(String value) {
            addCriterion("system_qrcode not like", value, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeIn(List<String> values) {
            addCriterion("system_qrcode in", values, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeNotIn(List<String> values) {
            addCriterion("system_qrcode not in", values, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeBetween(String value1, String value2) {
            addCriterion("system_qrcode between", value1, value2, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemQrcodeNotBetween(String value1, String value2) {
            addCriterion("system_qrcode not between", value1, value2, "systemQrcode");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightIsNull() {
            addCriterion("system_copyright is null");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightIsNotNull() {
            addCriterion("system_copyright is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightEqualTo(String value) {
            addCriterion("system_copyright =", value, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightNotEqualTo(String value) {
            addCriterion("system_copyright <>", value, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightGreaterThan(String value) {
            addCriterion("system_copyright >", value, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightGreaterThanOrEqualTo(String value) {
            addCriterion("system_copyright >=", value, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightLessThan(String value) {
            addCriterion("system_copyright <", value, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightLessThanOrEqualTo(String value) {
            addCriterion("system_copyright <=", value, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightLike(String value) {
            addCriterion("system_copyright like", value, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightNotLike(String value) {
            addCriterion("system_copyright not like", value, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightIn(List<String> values) {
            addCriterion("system_copyright in", values, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightNotIn(List<String> values) {
            addCriterion("system_copyright not in", values, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightBetween(String value1, String value2) {
            addCriterion("system_copyright between", value1, value2, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSystemCopyrightNotBetween(String value1, String value2) {
            addCriterion("system_copyright not between", value1, value2, "systemCopyright");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsIsNull() {
            addCriterion("systeam_external_js is null");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsIsNotNull() {
            addCriterion("systeam_external_js is not null");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsEqualTo(String value) {
            addCriterion("systeam_external_js =", value, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsNotEqualTo(String value) {
            addCriterion("systeam_external_js <>", value, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsGreaterThan(String value) {
            addCriterion("systeam_external_js >", value, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsGreaterThanOrEqualTo(String value) {
            addCriterion("systeam_external_js >=", value, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsLessThan(String value) {
            addCriterion("systeam_external_js <", value, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsLessThanOrEqualTo(String value) {
            addCriterion("systeam_external_js <=", value, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsLike(String value) {
            addCriterion("systeam_external_js like", value, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsNotLike(String value) {
            addCriterion("systeam_external_js not like", value, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsIn(List<String> values) {
            addCriterion("systeam_external_js in", values, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsNotIn(List<String> values) {
            addCriterion("systeam_external_js not in", values, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsBetween(String value1, String value2) {
            addCriterion("systeam_external_js between", value1, value2, "systeamExternalJs");
            return (Criteria) this;
        }

        public Criteria andSysteamExternalJsNotBetween(String value1, String value2) {
            addCriterion("systeam_external_js not between", value1, value2, "systeamExternalJs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_information
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 15 02:46:01 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_information
     *
     * @mbg.generated Sat Jun 15 02:46:01 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}