package anonymous.developer.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_password
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_picture_url
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private String userPictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_sex
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private Byte userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_age
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private Byte userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_create_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private Date userCreateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_update_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private Date userUpdateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_last_login_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private Date userLastLoginDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_email
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    private String userEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_password
     *
     * @return the value of users.user_password
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_password
     *
     * @param userPassword the value for users.user_password
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_picture_url
     *
     * @return the value of users.user_picture_url
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public String getUserPictureUrl() {
        return userPictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_picture_url
     *
     * @param userPictureUrl the value for users.user_picture_url
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserPictureUrl(String userPictureUrl) {
        this.userPictureUrl = userPictureUrl == null ? null : userPictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_sex
     *
     * @return the value of users.user_sex
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public Byte getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_sex
     *
     * @param userSex the value for users.user_sex
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserSex(Byte userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_age
     *
     * @return the value of users.user_age
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public Byte getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_age
     *
     * @param userAge the value for users.user_age
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserAge(Byte userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_create_datetime
     *
     * @return the value of users.user_create_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public Date getUserCreateDatetime() {
        return userCreateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_create_datetime
     *
     * @param userCreateDatetime the value for users.user_create_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserCreateDatetime(Date userCreateDatetime) {
        this.userCreateDatetime = userCreateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_update_datetime
     *
     * @return the value of users.user_update_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public Date getUserUpdateDatetime() {
        return userUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_update_datetime
     *
     * @param userUpdateDatetime the value for users.user_update_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserUpdateDatetime(Date userUpdateDatetime) {
        this.userUpdateDatetime = userUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_last_login_datetime
     *
     * @return the value of users.user_last_login_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public Date getUserLastLoginDatetime() {
        return userLastLoginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_last_login_datetime
     *
     * @param userLastLoginDatetime the value for users.user_last_login_datetime
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserLastLoginDatetime(Date userLastLoginDatetime) {
        this.userLastLoginDatetime = userLastLoginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_email
     *
     * @return the value of users.user_email
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_email
     *
     * @param userEmail the value for users.user_email
     *
     * @mbg.generated Sat Jun 15 03:00:35 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }
}